name: m2release
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.2.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - cffi=1.13.2=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.8=py36h1ba5d50_0
  - cython=0.29.14=py36he6710b0_0
  - dill=0.2.9=py36_0
  - idna=2.8=py36_0
  - intel-openmp=2019.5=281
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.5=281
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.5.6=py36h6bb024c_1
  - ncurses=6.1=he6710b0_1
  - openjdk=8.0.152=h46b5887_1
  - openssl=1.1.1=h7b6447c_0
  - pip=19.3.1=py36_0
  - pycparser=2.19=py_0
  - pyopenssl=19.1.0=py36_0
  - pysocks=1.7.1=py36_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_0
  - setuptools=41.6.0=py36_0
  - six=1.13.0=py36_0
  - spacy=2.0.11=py36h04863e7_2
  - sqlite=3.30.1=h7b6447c_0
  - termcolor=1.1.0=py36_1
  - thinc=6.11.2=py36hedc7406_1
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - urllib3=1.24.2=py36_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.1
    - cycler==0.10.0
    - cymem==1.31.2
    - cytoolz==0.9.0.1
    - future==0.17.1
    - grpcio==1.25.0
    - h5py==2.8.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==2.2.3
    - msgpack==0.6.2
    - multiprocess==0.70.9
    - murmurhash==0.28.0
    - numpy==1.16.4
    - pathlib==1.0.1
    - pathos==0.2.3
    - pillow==6.2.1
    - plac==0.9.6
    - pox==0.2.7
    - ppft==1.6.6.1
    - preshed==1.0.1
    - protobuf==3.10.0
    - pycocotools==2.0.0
    - pyparsing==2.4.5
    - python-dateutil==2.8.1
    - pytz==2019.3
    - regex==2017.4.5
    - tensorboard==1.14.0
    - torch==1.1.0
    - torchvision==0.3.0
    - tqdm==4.32.2
    - ujson==1.35
    - werkzeug==0.16.0
    - wrapt==1.10.11

